spring:
  liquibase:
    change-log: db/db.changelog-main.yml

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

server:
  port: 9090